### PR TITLE
Fix Patch & Wait

### LINKED ISSUE #13: patch and wait
I am noticing a potential issue in the last lines of the model's save function. When I try to make a patch and I also want to wait to make the changes such as:
```javascript
model.save({ 
    /*attrs*/
}, {
    patch: true,
    wait: true
}
```
the attrs set in `sync` are set to the serialization to the model.
````javascript
        if (method === 'patch') options.attrs = attrs;
        // if we're waiting we haven't actually set our attributes yet so
        // we need to do make sure we send right data
        if (options.wait) options.attrs = _.extend(model.serialize(), attrs);
        xhr = this.sync(method, this, options);

        return xhr;
````

if I am sending a patch I definitely don't want to send over EVERYTHING that is attached to my model but maybe I am missing a point here.

### LINKED ISSUE #53: Save options wait:true and patch:true are mutually exclusive
If this is intentional, then close my issue, otherwise this needs a look.

https://github.com/AmpersandJS/ampersand-model/blob/master/ampersand-model.js#L64
and
https://github.com/AmpersandJS/ampersand-model/blob/master/ampersand-model.js#L67

Line 67 overrides what was done on 64 if both wait and patch are true.

### PR DESCRIPTION
**Pull request by pgilad**
- Originally written by @nickryall at https://github.com/AmpersandJS/ampersand-model/pull/23
- Fixes #13
- Fixes #23
- Fixes #53

### CODE REVIEW

**Comment by lukekarrys** [comment]
+1

**Comment by kamilogorek** [comment]
Looks good! +1

**Comment by lukekarrys** [comment]
@pgilad Giving you npm access now

**Comment by pgilad** [comment]
Thanks @lukekarrys. Is this a minor release?

**Comment by lukekarrys** [comment]
Seems like a patch to me since no new functionality was added.

**Pull request merged**
