### PR TITLE
Update ampersand-sync dep to 4.0.3

### LINKED ISSUE #71: update ampersand-sync to 4.0.3
4.0.3 has some nice bug fixes, namely https://github.com/AmpersandJS/ampersand-sync/pull/72

### PR DESCRIPTION
**Pull request by meandavejustice**
- bump version from 4.0.2 to 4.0.3
- fixes #71 #18

### CODE REVIEW

**Comment by meandavejustice** [comment]
tests are failing because I have no saucelabs creds https://travis-ci.org/AmpersandJS/ampersand-model/builds/117793252#L308

**Comment by wraithgar** [comment]
+1 this would be a patch release on this repo.

**Comment by lukekarrys** [comment]
+1

**Comment by wraithgar** [comment]
published as `v6.0.3`

**Pull request merged**
