### PR TITLE
rev deps, notably &-state to 4.6.0 (minor bump)

### PR DESCRIPTION
**Pull request by cdaringe**
# problem statement
no problem.  just wanting to stay fresh ♨️ 🍊

# solution
rev those dependencies!

### CODE REVIEW

**Comment by lukekarrys** [comment]
+1

**Comment by kamilogorek** [comment]
+1

**Comment by cdaringe** [comment]
added publish scripts.  published as 6.0.2.

**Comment by cdaringe** [comment]
whoops--nm.  don't have publish access.  publish scripts are pushed to github, tho

**Comment by wraithgar** [comment]
I added you to `ampersand-model` would you please try to publish again?

**Comment by cdaringe** [comment]
gladly.  looks like it took!

**Pull request merged**
