### PR TITLE
update ampersand-sync to v3

### PR DESCRIPTION
**Pull request by lukekarrys**

### CODE REVIEW

**Comment by bear** [comment]
@lukekarrys any reason to not merge this?

**Comment by lukekarrys** [comment]
Since `ampersand-sync` has some outstanding issues that will require a major version bump, I think we should hold off on merging this until we have completed those, since any major sync version bump will also require a major version bump here. I put them all into a `v4` milestone over on that repo so that they can be tracked over there.

**Comment by gonsfx** [comment]
Any progress on this? We need the new `ampersand-sync` version now! :)

**Comment by lukekarrys** [comment]
Closing in favor of #42

**Pull request closed without merging**
