### PR TITLE
Update deps

### PR DESCRIPTION
**Pull request by lukekarrys**
- Removes unused devDeps
- Further update deps that were started in #25

### CODE REVIEW

**Comment by lukekarrys** [comment]
I dont think this will require a publish as the only non-dev dependencies that got updated were minor version bumps.

**Comment by wraithgar** [comment]
Are we sure about going to underscore 1.7.0?

**Comment by wraithgar** [comment]
I preemptively removed the underscore bump and am now a +1 on this

**Comment by kamilogorek** [comment]
lgtm +!

**Comment by wraithgar** [comment]
The `state` bump at least was a minor which means `model` would inherit those, making this minor?

**Pull request merged**
