### PR TITLE
Organize code. Add files to package.json

### PR DESCRIPTION
**Pull request by pgilad**

### CODE REVIEW

**Comment by wraithgar** [comment]
+1

**Comment by lukekarrys** [comment]
+1

**Comment by lukekarrys** [comment]
Is this worth publishing or should it just wait until the next release?

**Comment by wraithgar** [comment]
Normally I'd say wait but there aren't any other PRs that appear to be imminent so :shipit: @lukekarrys

**Comment by lukekarrys** [comment]
Published as `v5.0.3`.

**Pull request merged**
