### PR TITLE
replace underscore with standalone lodash modules; relegate underscore t...

### PR DESCRIPTION
**Pull request by dhritzkiv**
...o be a devDependency (for tests)

As per http://blog.andyet.com/2015/03/25/amped-down

### CODE REVIEW

**Comment by lukekarrys** [comment]
What do we think about dropping underscore from devDeps and using lodash there? I'm concerned about underscores lack of semver breaking tests in the future.

**Comment by wraithgar** [comment]
+1

**Comment by kamilogorek** [comment]
Looks good.

**Comment by wraithgar** [comment]
published as `v5.0.1`

**Pull request merged**
