### PR TITLE
Bump ampersand-state to ^5.0.1

### PR DESCRIPTION
**Pull request by janpaul123**
So we can benefit from https://github.com/AmpersandJS/ampersand-state/pull/235 in ampersand-model.

### CODE REVIEW

**Comment by janpaul123** [comment]
Could you have a look at this @pgilad @lukekarrys @wraithgar?

**Comment by pgilad** [comment]
Tests pass for me locally, I would also take the chance to update lodash deps before major bumping here

**Comment by janpaul123** [comment]
Yeah, that would be great. Any way I could help with that?

**Comment by cdaringe** [comment]
+1

**Comment by pgilad** [comment]
Published as version 7.0.0 (https://github.com/AmpersandJS/ampersand-model/commit/6042bf1b7fb4d9399f4bc05160c5bcccc3ff4871)

**Comment by janpaul123** [comment]
Great, thanks!!

**Pull request merged**
