### PR TITLE
add fix for how amp sync treats error callbacks

### PR DESCRIPTION
**Pull request by engenb**
this pull request addresses #38

### CODE REVIEW

**Comment by contra** [comment]
Any ETA on merging this? Causing a ton of issues with some apps we have

**Comment by lukekarrys** [comment]
+1, fix looks good to me. I'll find another @AmpersandJS/core-team person to second this and we'll get it merged/published.

**Comment by wraithgar** [comment]
+1 do it @lukekarrys

**Comment by HenrikJoreteg** [comment]
+1 @lukekarrys @wraithgar. :shipit:

**Comment by contra** [comment]
What's the process for merging PRs? Documented anywhere? Seems a tad slow to wait for the whole team to chime in on a simple bug fix that includes tests

**Comment by HenrikJoreteg** [comment]
published as `4.1.0` silly me fatfingered it as a minor instead of patch release. But anyway, there it is.

Thanks @engenb!

@contra the typical process we have is 2 plus ones: http://ampersandjs.com/learn/bug-triage-process#pull-requests

**Comment by HenrikJoreteg** [comment]
We're also in the process of assigning lead maintainers for each repo so it's clearer who's the primary on each one.

**Pull request merged**
