### PR TITLE
Fix for Patch & Wait

### PR DESCRIPTION
**Pull request by nickryall**
Fix to prevent all attributes being sent with request when using 

    model.save(attrs, { patch: true, wait: true });

Related issue here:

https://github.com/AmpersandJS/ampersand-model/issues/13

### CODE REVIEW

**Comment by nickryall** [comment]
I say this is a bug fix rather than an enhancement.  The expected behaviour when sending PATCH requests is to only send the specified attributes.

**Comment by wraithgar** [comment]
Yeah this makes sense. Should it have a quick test?

**Comment by nickryall** [comment]
@wraithgar Let me check if there is an existing test in the backbone tests that are pulled in. If not I'll get one written ASAP.

**Comment by nickryall** [comment]
Added tested for with PATCH and save with PATCH and `wait`

**Comment by pgilad** [comment]
Hey @nickryall I want to review this PR (finally) - can you rebase all commits into 1?

**Comment by nickryall** [comment]
@pgilad  Apologies, I just saw your comment. Sure I'll get this done today.

**Comment by pgilad** [comment]
Rebased and re added new PR #58. Thanks!

**Pull request closed without merging**
