### PR TITLE
update to ampersand sync v3

### PR DESCRIPTION
**Pull request by lukekarrys**
Doing a new PR since #26 is out of date and #40 bumped the package version in the package.json.

### CODE REVIEW

**Comment by wraithgar** [comment]
+1 once travis completes. should have done this awhile ago.

**Comment by latentflip** [comment]
+1 pending tests

**Comment by lukekarrys** [comment]
v5.0.0 has been published to include the latest ampersand-sync

**Comment by constantx** [comment]
:+1:

**Pull request merged**
